### ISSUE TITLE
solicitud vacaciones -colega ecuador

### ISSUE THREAD

**Issue by ydnas22** [ydnas22/SGV#14]
los dias de fin de semana que se deben descontar a un colega por periodo son cada 5 dias utiles de un periodo dos fines de semana, 
por ejemplo tengo dos periodos de 15 dias
periodo1:15
periodo2:15

pido 15 dias utiles de vacaciones
el sistema actualmente me toma 6 dias de fin de semana y deberia ser solamente 4

porque estoy tomando 

11 dias utiles del periodo1  siguiendo la regla de cada 5 dos dias de fin de semana seria 4 dias de fin de semana
4 dias utiles del periodo 2: guiendo la regla de cada 5 dos dias de fin de semana seria 0 dias de fin de semana

**Comment by dyland30** [comment]
se corrigió, ahora el sistema toma fines de semana correspondientes al periodo.
