### ISSUE TITLE
CESAR UN EMPLEADO

### ISSUE THREAD

**Issue by ydnas22** [ydnas22/SGV#16]
EL SISTEMA NO ME DEJA CESAR UN EMPLEADO CON LA FECHA ACTUAL O ANTERIOR, ME SALE QUE EL EMPLEADO NO SE PUEDE CESAR CON UNA FECHA ANTERIOR A LA FECHA ACTUAL

**Comment by dyland30** [comment]
Me parece que este fue un requerimiento, que validemos que la fecha de cese no sea anterior a la fecha actual

**Comment by dyland30** [comment]
se incluira la fecha actual

**Comment by dyland30** [comment]
realizado!
