### ISSUE TITLE
MANTENIMIENTO EMPLEADOS-ECUADOR Y PERU

### ISSUE THREAD

**Issue by ydnas22** [ydnas22/SGV#17]
NO DEBERIA DEJARTE REGISTRAR UN EMPLEADO CON FECHA DE INGRESO MAYOR A LA FECHA ACTUAL PK SE CREAN UN MONTON DE PERIODOS CON NUMEROS DE DIAS EN NEGATIVOS -232 -336 -334

**Comment by dyland30** [comment]
jajaja interesante

**Comment by dyland30** [comment]
realizado!
