### ISSUE TITLE
MANTENIMIENTO EMPLEADOS - PERU Y ECUADOR

### ISSUE THREAD

**Issue by ydnas22** [ydnas22/SGV#4]
SE DEBE VALIDAR QUE EL NUMERO DE EMPLOYEE ID NO SE PUEDA DUPLICAR  AL SALIR DEL CAMPO, SALVO EN EL CASO DE Q UN EMPLEADO HAYA CESADO Y VUELVA A REINGRESAR ESTO PARA AMBOS PAISES

**Comment by dyland30** [comment]
realizado, se agregó el mensaje de alerta y la opción para asignar los roles al usuario del empleado
