### ISSUE TITLE
MANTENIMIENTO DE EMPLEADOS PERU Y ECUADOR

### ISSUE THREAD

**Issue by ydnas22** [ydnas22/SGV#7]
LOS DATOS DE NOMBRES, APELLIDOS SE DEBEN PASAR A MAYUSCULAS PARA EVITAR QUE SE GUARDEN ALGUNAS VECES EN MAYUSCULAS Y OTRAS EN MINUSCULAS

**Comment by dyland30** [comment]
realizado
