### ISSUE TITLE
MANTENIMIENTO DE EMPLEADOS PERU Y ECUADOR

### ISSUE THREAD

**Issue by ydnas22** [ydnas22/SGV#8]
VER UNA FORMA DE BORRAR LAS COKIES PK CUANDO ESTOY REGISTRANDO ROLES DE USUARIO A EMPLEADOS, AUTOMATICAMENTE SE AGREGAN LOS ROLES QUE AGREGUE EN EL ANTERIOR USUARIO

**Comment by dyland30** [comment]
Al guardar el empleado se debe borrar de la sesion la lista de roles seleccionados
